version: '3.9'

services:
  mongo:
    image: mongo:6
    restart: always
    volumes:
      - mongo_data:/data/db
    ports:
      - '27017:27017'
    command: ['mongod', '--replSet', 'rs0', '--bind_ip_all']

  redis:
    image: redis:7
    restart: always
    ports:
      - '6379:6379'

  server:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - DATABASE_URL=mongodb://root:root@mongo:27017/blog?authSource=admin&replicaSet=rs0
      - REDIS_URL=redis://redis:6379
    depends_on:
      - mongo
      - redis
    ports:
      - '5000:5000'
    command: npm run start:prod

  client:
    build:
      context: ../client_blog
      dockerfile: Dockerfile
    restart: always
    ports:
      - '80:80'
    depends_on:
      - server

volumes:
  mongo_data:
